=== laszlobodnar14/D1H8VPWEBXML/XML_FÉLÉVES_D1H8VP/XMLSchemaD1H8VP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Etterem_D1H8VP">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pizzazo" type="PizzazoTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Beszallito" type="BeszallitoTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Futar" type="FutarTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Vevo" type="VevoTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Bankkartya" type="BankkartyaTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Pizza" type="PizzaTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="Rendeles" type="RendelesTipus" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="PizzazoPK">
            <xs:selector xpath="Pizzazo"/>
            <xs:field xpath="@PizzazoID"/>
        </xs:key>
        <xs:key name="BeszallitoPK">
            <xs:selector xpath="Beszallito"/>
            <xs:field xpath="@BeszallitoID"/>
        </xs:key>
        <xs:key name="FutarPK">
            <xs:selector xpath="Futar"/>
            <xs:field xpath="@FutarID"/>
        </xs:key>
        <xs:key name="VevoPK">
            <xs:selector xpath="Vevo"/>
            <xs:field xpath="@VevoID"/>
        </xs:key>
        <xs:key name="BankkartyaPK">
            <xs:selector xpath="Bankkartya"/>
            <xs:field xpath="@Kartyaszam"/>
        </xs:key>
        <xs:key name="PizzaPK">
            <xs:selector xpath="Pizza"/>
            <xs:field xpath="@PizzaID"/>
        </xs:key>
        <xs:key name="RendelesPK">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@RendelesID"/>
        </xs:key>

        <xs:keyref name="Futar_Pizzazo_FK" refer="PizzazoPK">
            <xs:selector xpath="Futar"/>
            <xs:field xpath="@PizzazoID"/>
        </xs:keyref>

        <xs:keyref name="Pizza_Pizzazo_FK" refer="PizzazoPK">
            <xs:selector xpath="Pizza"/>
            <xs:field xpath="@PizzazoID"/>
        </xs:keyref>

        <xs:keyref name="Bankkartya_Vevo_FK" refer="VevoPK">
            <xs:selector xpath="Bankkartya"/>
            <xs:field xpath="@VevoID"/>
        </xs:keyref>

        <xs:keyref name="Rendeles_Vevo_FK" refer="VevoPK">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@VevoID"/>
        </xs:keyref>

        <xs:keyref name="Rendeles_Pizza_FK" refer="PizzaPK">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@PizzaID"/>
        </xs:keyref>

    </xs:element>

    <xs:complexType name="CimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"/>
            <xs:element name="IRSZ" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name="Hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PizzazoTipus">
        <xs:sequence>
            <xs:element name="Nyitvatartas" type="xs:string"/>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Telefonszam" type="xs:string"/>
            <xs:element name="Weboldal" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="PizzazoID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="BeszallitoTipus">
        <xs:sequence>
            <xs:element name="Elerhetoseg" type="xs:string"/>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Cim" type="CimTipus"/>
        </xs:sequence>
        <xs:attribute name="BeszallitoID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="FutarTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Telefonszam" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="FutarID" type="xs:string" use="required"/>
        <xs:attribute name="PizzazoID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="VevoTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Telefonszam" type="xs:string"/>
            <xs:element name="Cim" type="CimTipus"/>
        </xs:sequence>
        <xs:attribute name="VevoID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="BankkartyaTipus">
        <xs:sequence>
            <xs:element name="Bank" type="xs:string"/>
            <xs:element name="Lejarati_datum" type="xs:date"/>
            <xs:element name="Tipus" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="Kartyaszam" type="xs:string" use="required"/>
        <xs:attribute name="VevoID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="PizzaTipus">
        <xs:sequence>
            <xs:element name="Teljes_ar" type="xs:unsignedInt"/>
            <xs:element name="Pizza_neve" type="xs:string"/>
            <xs:element name="Feltetek">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Feltet" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Meretek">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Meret" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="PizzaID" type="xs:string" use="required"/>
        <xs:attribute name="PizzazoID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="RendelesTipus">
        <xs:attribute name="RendelesID" type="xs:string" use="required"/>
        <xs:attribute name="VevoID" type="xs:string" use="required"/>
        <xs:attribute name="PizzaID" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== laszlobodnar14/D1H8VPWEBXML/etterem_output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Etterem_D1H8VP xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaD1H8VP.xsd">
    <Pizzazo PizzazoID="P1">
        <Nyitvatartas>10:00-22:00</Nyitvatartas>
        <Nev>Miskolc Pizza</Nev>
        <Telefonszam>06301234567</Telefonszam>
        <Weboldal>miskolcpizza.hu</Weboldal>
    </Pizzazo>
    <Beszallito BeszallitoID="B1">
        <Elerhetoseg>info@beszal1.hu</Elerhetoseg>
        <Nev>Beszallito1</Nev>
        <Cim>
            <Varos>Kazincbarcika</Varos>
            <IRSZ>3700</IRSZ>
            <Utca>Joszerencset ut</Utca>
            <Hazszam>2</Hazszam>
        </Cim>
    </Beszallito>
    <Futar FutarID="F1" PizzazoID="P1">
        <Nev>James Bond</Nev>
        <Telefonszam>70115452</Telefonszam>
    </Futar>
    <Vevo VevoID="V1">
        <Nev>V치s치r L칩</Nev>
        <Telefonszam>20198772</Telefonszam>
        <Cim>
            <Varos>Kazincbarcika</Varos>
            <IRSZ>3700</IRSZ>
            <Utca>J칩zsef attila utca</Utca>
            <Hazszam>7</Hazszam>
        </Cim>
    </Vevo>
    <Bankkartya Kartyaszam="17846573498579" VevoID="V1">
        <Bank>OTP Bank</Bank>
        <Lejarati_datum>2026-12-31</Lejarati_datum>
        <Tipus>Mastercard</Tipus>
    </Bankkartya>
    <Pizza PizzaID="PIZ2" PizzazoID="P1">
        <Teljes_ar>3200</Teljes_ar>
        <Pizza_neve>Son goku</Pizza_neve>
        <Feltetek>
            <Feltet>Paradicsom</Feltet>
            <Feltet>Sajt</Feltet>
            <Feltet>Sonka</Feltet>
            <Feltet>Kukorica</Feltet>
        </Feltetek>
        <Meretek>
            <Meret>32cm</Meret>
            <Meret>45cm</Meret>
        </Meretek>
    </Pizza>
    <Rendeles PizzaID="PIZ2" RendelesID="R1" VevoID="V1"/>
</Etterem_D1H8VP>

=== laszlobodnar14/D1H8VPWEBXML/Etterem_D1H8VP_modositasok.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Etterem_D1H8VP xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaD1H8VP.xsd">
        
    <!--Pizzazo-->
        
    <Pizzazo PizzazoID="P1">
                
        <Nyitvatartas>10:00-22:00</Nyitvatartas>
                
        <Nev>Miskolc Pizza</Nev>
                
        <Telefonszam>06301234567</Telefonszam>
                
        <Weboldal>miskolcpizza.hu</Weboldal>
            
    </Pizzazo>
        
    <Pizzazo PizzazoID="P2">
                
        <Nyitvatartas>08:00-20:00</Nyitvatartas>
                
        <Nev>Kiraly Pizzeria</Nev>
                
        <Telefonszam>307654321</Telefonszam>
                
        <Weboldal>kiraly.hu</Weboldal>
            
    </Pizzazo>
        
    <!--Beszallito-->
        
    <Beszallito BeszallitoID="B1">
                
        <Elerhetoseg>info@beszal1.hu</Elerhetoseg>
                
        <Nev>Beszallito1</Nev>
                
        <Cim>
                        
            <Varos>Kazincbarcika</Varos>
                        
            <IRSZ>3700</IRSZ>
                        
            <Utca>Joszerencset ut</Utca>
                        
            <Hazszam>2</Hazszam>
                    
        </Cim>
            
    </Beszallito>
        
    <Beszallito BeszallitoID="B2">
                
        <Elerhetoseg>info@beszal2.hu</Elerhetoseg>
                
        <Nev>Beszallito2</Nev>
                
        <Cim>
                        
            <Varos>Kazincbarcika</Varos>
                        
            <IRSZ>3700</IRSZ>
                        
            <Utca>Dobo istvan ter</Utca>
                        
            <Hazszam>7</Hazszam>
                    
        </Cim>
            
    </Beszallito>
        
    <!--Futar-->
        
    <Futar FutarID="F1" PizzazoID="P2">
                
        <Nev>James Bond</Nev>
                
        <Telefonszam>70115452</Telefonszam>
            
    </Futar>
        
    <Futar FutarID="F2" PizzazoID="P1">
                
        <Nev>Jack Sparrow</Nev>
                
        <Telefonszam>7036534444</Telefonszam>
            
    </Futar>
        
    <Futar FutarID="F3" PizzazoID="P2">
                
        <Nev>Nagy Sándor</Nev>
                
        <Telefonszam>705543566</Telefonszam>
            
    </Futar>
        
    <!--Vevo-->
        
    <Vevo VevoID="V1">
                
        <Nev>Vásár Ló</Nev>
                
        <Telefonszam>20198772</Telefonszam>
                
        <Cim>
                        
            <Varos>Kazincbarcika</Varos>
                        
            <IRSZ>3700</IRSZ>
                        
            <Utca>József attila utca</Utca>
                        
            <Hazszam>7</Hazszam>
                     
        </Cim>
            
        <Email>vasar.lo@email.com</Email>
    </Vevo>
        
    <Vevo VevoID="V2">
                
        <Nev>K Anna</Nev>
                
        <Telefonszam>203342344</Telefonszam>
                
        <Cim>
                        
            <Varos>Miskolc</Varos>
                        
            <IRSZ>3700</IRSZ>
                        
            <Utca>Dobo utca</Utca>
                        
            <Hazszam>3</Hazszam>
                    
        </Cim>
            
    </Vevo>
        
    <!--Bankkartya-->
        
    <Bankkartya Kartyaszam="17846573498579" VevoID="V1">
                
        <Bank>OTP Bank</Bank>
                
        <Lejarati_datum>2026-12-31</Lejarati_datum>
                
        <Tipus>Mastercard</Tipus>
            
    </Bankkartya>
        

    
    <!--Pizza-->
        
    <Pizza PizzaID="PIZ1" PizzazoID="P1">
                
        <Teljes_ar>2990</Teljes_ar>
                
        <Pizza_neve>Margarita</Pizza_neve>
                
        <Feltetek>
                        
            <Feltet>Paradicsom</Feltet>
                        
            <Feltet>Sajt</Feltet>
                        
            <Feltet>Oregeno</Feltet>
                    
            <Feltet>Gomba</Feltet>
        </Feltetek>
                
        <Meretek>
                        
            <Meret>32cm</Meret>
                    
        </Meretek>
            
    </Pizza>
        
    <Pizza PizzaID="PIZ2" PizzazoID="P1">
                
        <Teljes_ar>3200</Teljes_ar>
                
        <Pizza_neve>Son goku</Pizza_neve>
                
        <Feltetek>
                        
            <Feltet>Paradicsom</Feltet>
                        
            <Feltet>Sajt</Feltet>
                        
            <Feltet>Sonka</Feltet>
                        
            <Feltet>Kukorica</Feltet>
                    
        </Feltetek>
                
        <Meretek>
                        
            <Meret>32cm</Meret>
                        
            <Meret>45cm</Meret>
                    
        </Meretek>
            
    </Pizza>
        
    <Pizza PizzaID="PIZ3" PizzazoID="P2">
                
        <Teljes_ar>3500</Teljes_ar>
                
        <Pizza_neve>Magyaros</Pizza_neve>
                
        <Feltetek>
                        
            <Feltet>Paradicsom</Feltet>
                        
            <Feltet>Sajt</Feltet>
                        
            <Feltet>Kolbász</Feltet>
                        
            <Feltet>Hagyma</Feltet>
                        
            <Feltet>Erős paprika</Feltet>
                    
        </Feltetek>
                
        <Meretek>
                        
            <Meret>30cm</Meret>
                    
        </Meretek>
            
    </Pizza>
        
    <!--Rendeles-->
        
    <Rendeles PizzaID="PIZ2" RendelesID="R1" VevoID="V1"/>
        
    <Rendeles PizzaID="PIZ1" RendelesID="R2" VevoID="V2"/>
        
    <Rendeles PizzaID="PIZ3" RendelesID="R3" VevoID="V2"/>
    
</Etterem_D1H8VP>
